<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260223/blob/main/20260321_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
如何定位html區塊(你要的)

前端(客戶端):
網頁如何呈現給客戶
1. HTML: 網頁內容(區塊名字/屬性/顯示)
2. CSS: 給html區塊加上排版
3. JavaScript程式: 控制網頁動態

爬蟲:
CSS語法(!): 幫助定位你要的區塊
JavaScript(X): 送出隱藏網址

後端(伺服器端):
1. 接收http request(apache/nginx...)
2. 要有個背景程式來處理request(Python: Flask, Django, FastAPI)
3. 處理request的時候會需要額外輔助(資料庫: SQL)
4. 背景程式把http response送回去

```



```
CSS語法: 定位區塊加上排版

1. 透過html名字來定位
a{
    background-color:red
}

class="分類1 分類2"
2. 透過class屬性做選擇
.分類{

}

id="唯一身分證"
3. 透過id屬性做選擇
#身分證{
}

```

In [16]:
import urllib.request as req
import bs4 as bs

def get_tabelog_page(num):
    # 1. 先準備list
    table = []

    url = "https://tabelog.com/tw/tokyo/rstLst/sweets/" + str(num) + "/?SrtT=rt"
    print(url)
    resp = req.urlopen(url)
    content = resp.read()
    html = bs.BeautifulSoup(content)

    # find/find_all
    rs = html.find_all("div", {"class":"list-rst__body"})
    for r in rs:
        # 拿到
        # 地點/type 評價 晚間價格 午間價格
        en = r.find("a", {"class":"list-rst__rst-name-target"})
        area_genre = r.find("div", {"class":"list-rst__area-genre"})
        rating = r.find("span", {"class":"c-rating__val"})
        prices = r.find_all("span", {"class":"c-rating-v3__val"})
        lunch = prices[0]
        dinner = prices[1]

        # 屬性/顯示: ["href"]/.get_text()
        en_href = en["href"]
        en_text = en.get_text().strip()
        area_genre_text = area_genre.get_text().strip()
        rating_text = rating.get_text().strip()
        lunch_text = lunch.get_text().strip()
        dinner_text = dinner.get_text().strip()

        # 印(ctrl + / 多行註解)
        # print(rating_text)
        # print(en_text)
        # print(en_href)
        # print(area_genre_text)
        # print(lunch_text)
        # print(dinner_text)

        # 2. 準備每一筆資料
        row = {
            "rating":rating_text,
            "name":en_text,
            "url":en_href,
            "area_genre":area_genre_text,
            "lunch_price":lunch_text,
            "dinner_price":dinner_text
        }
        table.append(row)
    return table

In [ ]:
# 只要做存檔, 就把格式變成JSON格式
# [danmu, danmu, danmu]  danmu: {}
import pandas as pd
total = []
for i in range(10):
    page = i + 1
    total = total + get_tabelog_page(page)

df = pd.DataFrame(total)
df.to_csv("tabelog.csv", encoding="utf-8")

In [36]:
# pandas兩大操作: 1. 過濾 2. 轉換
df = pd.read_csv("tabelog.csv", encoding="utf-8", index_col=0)
df

,rating,name,url,area_genre,lunch_price,dinner_price
0,4.26,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"參宮橋車站 / 法式料理, 牛排, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999"
1,4.23,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,"北參道車站 / 蛋糕, 西式甜點",-,"JPY 5,000 - JPY 5,999"
2,4.20,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,白金台車站 / 甜食,"JPY 20,000 - JPY 29,999","JPY 30,000 - JPY 39,999"
3,4.15,蒼菓,https://tabelog.com/tw/tokyo/A1307/A130703/132...,廣尾車站 / 甜食,"JPY 15,000 - JPY 19,999","JPY 15,000 - JPY 19,999"
4,4.00,Haruka Murooka,https://tabelog.com/tw/tokyo/A1307/A130701/132...,乃木坂車站 / 甜食,"JPY 20,000 - JPY 29,999","JPY 20,000 - JPY 29,999"
...,...,...,...,...,...,...
195,3.72,ZERO ONE CURRY A.o.D,https://tabelog.com/tw/tokyo/A1314/A131402/132...,"田町車站 / 印度料理, 印度咖哩, 蛋糕","JPY 2,000 - JPY 2,999","JPY 1,000 - JPY 1,999"
196,3.72,Paul Bassett 澀谷Hikarie ShinQs 東橫之簾街店,https://tabelog.com/tw/tokyo/A1303/A130301/131...,"澀谷車站 / 咖啡店, 蛋糕, 鬆餅",- JPY 999,- JPY 999
197,3.72,Usagiya CAFE,https://tabelog.com/tw/tokyo/A1311/A131101/131...,"上野廣小路車站 / 咖啡店, 鬆餅, 刨冰","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999"
198,3.72,森乃園,https://tabelog.com/tw/tokyo/A1302/A130204/130...,人形町車站 / 軟冰淇淋,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999"
199,3.72,羽二重團子 本店,https://tabelog.com/tw/tokyo/A1311/A131105/130...,"日暮里車站 / 日式點心, 日式甜點店",- JPY 999,- JPY 999

In [ ]:
# 最簡單轉換
# pandas兩個型態: 1. DataFrame(有行有列) 2. Series(一列/一行) -> list
df["rating"] * 2

```
Python世界裡:
Everything is an object!!
每個東西都一定有形態, 每個型態都有它可以做的操作

字典型態: dic 操作: [key]

以前: 每個功能都一定要加()

功能型態: int 操作: (4.6)
(還沒做的步驟集合)   (真的執行一遍)
功能: 把很多步驟聚集再一起, 變成一個大步驟

不加小括號: 還沒打開錦囊
加小括號: 打開照做一遍



```

In [31]:
# 轉換操作裡: 提供一份錦囊, 讓他可以對每一格()依次
# series.apply(錦囊)
def func(s):
    return s ** 0.5

df["rating"].apply(func)

0      2.063977
1      2.056696
2      2.049390
3      2.037155
4      2.000000
         ...
195    1.928730
196    1.928730
197    1.928730
198    1.928730
199    1.928730
Name: rating, Length: 200, dtype: float64

In [37]:
def func(s):
    s_spl = s.split(" / ")
    if len(s_spl) == 1:
        area = "-"
        genre = s_spl[0]
    else:
        area = s_spl[0]
        genre = s_spl[1]
    result = {
        "area":area,
        "genre":genre
    }
    return pd.Series(result)

extra = df["area_genre"].apply(func)
df = pd.concat([df, extra], axis=1)
df = df.drop("area_genre", axis=1)
df

,rating,name,url,lunch_price,dinner_price,area,genre
0,4.26,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",參宮橋車站,"法式料理, 牛排, 蛋糕"
1,4.23,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,-,"JPY 5,000 - JPY 5,999",北參道車站,"蛋糕, 西式甜點"
2,4.20,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,"JPY 20,000 - JPY 29,999","JPY 30,000 - JPY 39,999",白金台車站,甜食
3,4.15,蒼菓,https://tabelog.com/tw/tokyo/A1307/A130703/132...,"JPY 15,000 - JPY 19,999","JPY 15,000 - JPY 19,999",廣尾車站,甜食
4,4.00,Haruka Murooka,https://tabelog.com/tw/tokyo/A1307/A130701/132...,"JPY 20,000 - JPY 29,999","JPY 20,000 - JPY 29,999",乃木坂車站,甜食
...,...,...,...,...,...,...,...
195,3.72,ZERO ONE CURRY A.o.D,https://tabelog.com/tw/tokyo/A1314/A131402/132...,"JPY 2,000 - JPY 2,999","JPY 1,000 - JPY 1,999",田町車站,"印度料理, 印度咖哩, 蛋糕"
196,3.72,Paul Bassett 澀谷Hikarie ShinQs 東橫之簾街店,https://tabelog.com/tw/tokyo/A1303/A130301/131...,- JPY 999,- JPY 999,澀谷車站,"咖啡店, 蛋糕, 鬆餅"
197,3.72,Usagiya CAFE,https://tabelog.com/tw/tokyo/A1311/A131101/131...,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",上野廣小路車站,"咖啡店, 鬆餅, 刨冰"
198,3.72,森乃園,https://tabelog.com/tw/tokyo/A1302/A130204/130...,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",人形町車站,軟冰淇淋
199,3.72,羽二重團子 本店,https://tabelog.com/tw/tokyo/A1311/A131105/130...,- JPY 999,- JPY 999,日暮里車站,"日式點心, 日式甜點店"